In [2]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_excel(r'E:\Study\HIT\2021.09.04-Before school\2019级2020年细则查询网址.xlsx')

In [18]:
df[:]

,序号,学院名称,查询链接网址,联系人,办公电话,测试
0,1,航天学院,http://sa.hit.edu.cn/2020/0714/c8330a244018/pa...,白雪,86413018,1
1,2,电子与信息工程学院,http://seie.hit.edu.cn/_upload/article/files/a...,张老师,86413409,4
2,3,机电工程学院,http://myweb.hit.edu.cn/_s64/2020/0628/c3875a2...,宋建伟,86413808,89
3,4,材料科学与工程学院,http://mse.hit.edu.cn/_upload/article/files/26...,夏昕,86412943,3
4,5,能源科学与工程学院,http://power.hit.edu.cn/_upload/article/files/...,王海明,86413209,8
5,6,仪器学院,http://ise.hit.edu.cn/news/119/6790,刘伶俐,86415857,5
6,7,电气工程及自动化学院,http://hitee.hit.edu.cn/post/detail/11183,王文静,86413609,u234
7,8,化工与化学学院,http://chemeng.hit.edu.cn/2020/0623/c9576a2433...,吴婉琼,86413709,56
8,9,数学学院,http://math.hit.edu.cn/2020/0630/c10304a243507...,李艳华,86414209,1234
9,10,物理学院,http://physics.hit.edu.cn/12292/list.htm,王先杰,18686858490,7456
10,11,生命科学与技术学院,http://life.hit.edu.cn/gzzdjcyxz/list.htm,马文君,86416944,345673
11,12,经济与管理学院,http://som.hit.edu.cn/xspy/bkspy/gzzd.htm,李晶,86414002\nqq群号：978925719,4574
12,13,人文社科与法学学院,http://rwxy.hit.edu.cn/2020/0703/c6936a243639/...,邱实,86414609,7
13,14,土木工程学院,http://civil.hit.edu.cn/2020/0628/c8473a243428...,赵晓红,86282077,3
14,15,建筑学院,http://arch.hit.edu.cn/12220/list.htm,张正帅,86281132,23
15,16,交通学院,http://jtxy.hit.edu.cn/2020/0623/c6085a243305/...,李老师,86283779,512
16,17,计算学部,http://cs.hit.edu.cn/_upload/article/files/d9/...,金老师,86403509,512
17,18,外国语学院,http://fls.hit.edu.cn/bkspy/list.htm,李老师,86414509,51
18,19,环境学院,http://env.hit.edu.cn/2020/0715/c9485a244077/p...,魏 健,86282104,25

In [13]:
df['序号'].dtype

dtype('int64')

In [14]:
df['序号']=df['序号'].astype('float')

In [15]:
df[:2]

,序号,学院名称,查询链接网址,联系人,办公电话
0,1.0,航天学院,http://sa.hit.edu.cn/2020/0714/c8330a244018/pa...,白雪,86413018
1,2.0,电子与信息工程学院,http://seie.hit.edu.cn/_upload/article/files/a...,张老师,86413409

In [ ]:
df[df.年代=='2008\u200e']
df[df.年代=='2008\u200e']['年代'].values
df.loc[14934,'年代']=2008
df.loc[14934]
df['年代']=df['年代'].astypr('int')

In [16]:
df['时长']=df['时长'].astypr('int')#错
df[df['时长']]=='8U'#此时并不知道正确值  删
df.drop([31172],inplace=True)
df['时长']=df['时长'].astypr('int')#还错 那再删

KeyError: '时长'

In [20]:
df[df.测试=='u234']

,序号,学院名称,查询链接网址,联系人,办公电话,测试
6,7,电气工程及自动化学院,http://hitee.hit.edu.cn/post/detail/11183,王文静,86413609,u234

In [21]:
df[df.测试=='u234']['测试'].values

array(['u234'], dtype=object)

In [38]:
df.drop([6],inplace=True)

In [39]:
df['测试']=df['测试'].astype('float')

In [26]:
df[:2]

,序号,学院名称,查询链接网址,联系人,办公电话,测试
0,1,航天学院,http://sa.hit.edu.cn/2020/0714/c8330a244018/pa...,白雪,86413018,1.0
1,2,电子与信息工程学院,http://seie.hit.edu.cn/_upload/article/files/a...,张老师,86413409,4.0

In [29]:
df.sort_values(by='测试',ascending=False)[:5]

,序号,学院名称,查询链接网址,联系人,办公电话,测试
10,11,生命科学与技术学院,http://life.hit.edu.cn/gzzdjcyxz/list.htm,马文君,86416944,345673.0
9,10,物理学院,http://physics.hit.edu.cn/12292/list.htm,王先杰,18686858490,7456.0
11,12,经济与管理学院,http://som.hit.edu.cn/xspy/bkspy/gzzd.htm,李晶,86414002\nqq群号：978925719,4574.0
8,9,数学学院,http://math.hit.edu.cn/2020/0630/c10304a243507...,李艳华,86414209,1234.0
16,17,计算学部,http://cs.hit.edu.cn/_upload/article/files/d9/...,金老师,86403509,512.0

In [40]:
df.index=range(len(df))
df

,序号,学院名称,查询链接网址,联系人,办公电话,测试
0,1,航天学院,http://sa.hit.edu.cn/2020/0714/c8330a244018/pa...,白雪,86413018,1.0
1,2,电子与信息工程学院,http://seie.hit.edu.cn/_upload/article/files/a...,张老师,86413409,4.0
2,3,机电工程学院,http://myweb.hit.edu.cn/_s64/2020/0628/c3875a2...,宋建伟,86413808,89.0
3,4,材料科学与工程学院,http://mse.hit.edu.cn/_upload/article/files/26...,夏昕,86412943,3.0
4,5,能源科学与工程学院,http://power.hit.edu.cn/_upload/article/files/...,王海明,86413209,8.0
5,6,仪器学院,http://ise.hit.edu.cn/news/119/6790,刘伶俐,86415857,5.0
6,8,化工与化学学院,http://chemeng.hit.edu.cn/2020/0623/c9576a2433...,吴婉琼,86413709,56.0
7,9,数学学院,http://math.hit.edu.cn/2020/0630/c10304a243507...,李艳华,86414209,1234.0
8,10,物理学院,http://physics.hit.edu.cn/12292/list.htm,王先杰,18686858490,7456.0
9,11,生命科学与技术学院,http://life.hit.edu.cn/gzzdjcyxz/list.htm,马文君,86416944,345673.0
10,12,经济与管理学院,http://som.hit.edu.cn/xspy/bkspy/gzzd.htm,李晶,86414002,4574.0
11,13,人文社科与法学学院,http://rwxy.hit.edu.cn/2020/0703/c6936a243639/...,邱实,86414609,7.0
12,14,土木工程学院,http://civil.hit.edu.cn/2020/0628/c8473a243428...,赵晓红,86282077,3.0
13,15,建筑学院,http://arch.hit.edu.cn/12220/list.htm,张正帅,86281132,23.0
14,16,交通学院,http://jtxy.hit.edu.cn/2020/0623/c6085a243305/...,李老师,86283779,512.0
15,17,计算学部,http://cs.hit.edu.cn/_upload/article/files/d9/...,金老师,86403509,512.0
16,18,外国语学院,http://fls.hit.edu.cn/bkspy/list.htm,李老师,86414509,51.0
17,19,环境学院,http://env.hit.edu.cn/2020/0715/c9485a244077/p...,魏 健,86282104,25.0

In [41]:
df['办公电话'].mean()

1119742295.3888888

In [45]:
df[['办公电话','测试']].corr()

          办公电话        测试
办公电话  1.000000 -0.038546
测试   -0.038546  1.000000

In [49]:
len(df['测试'].unique())

16

In [50]:
df.to_excel(r'E:\Study\HIT\2021.09.04-Before school\2019级2020年细则查询网址2.xlsx')

#pd.set_option('max_columns',100)
#pd.set_option('max_rows',100)设置显示100行100列

In [56]:
pd.pivot_table(df,index=['测试'],values=['办公电话','序号'],aggfunc={'办公电话':np.mean,'序号':np.sum},fill_value=0)

                 办公电话  序号
测试
1.0          86413018   1
3.0          86347510  18
4.0          86413409   2
5.0          86415857   6
7.0          86414609  13
8.0          86413209   5
23.0         86281132  15
25.0         86282104  19
51.0         86414509  18
56.0         86413709   8
89.0         86413808   3
512.0        86343644  33
1234.0       86414209   9
4574.0       86414002  12
7456.0    18686858490  10
345673.0     86416944  11

#多个索引 只对C统计   pd.pivot_table(df,index=['测试','B'],values=['C','D'],aggfunc=[np.sum,np.mean])

In [57]:
table=pd.pivot_table(df,index=['测试'],values=['办公电话','序号'],aggfunc={'办公电话':np.mean,'序号':np.sum},fill_value=0)

In [58]:
type(table)

pandas.core.frame.DataFrame

In [60]:
table[table.index==3]

         办公电话  序号
测试
3.0  86347510  18

In [63]:
table.sort_values('序号',ascending=False)

                 办公电话  序号
测试
512.0        86343644  33
25.0         86282104  19
3.0          86347510  18
51.0         86414509  18
23.0         86281132  15
7.0          86414609  13
4574.0       86414002  12
345673.0     86416944  11
7456.0    18686858490  10
1234.0       86414209   9
56.0         86413709   8
5.0          86415857   6
8.0          86413209   5
89.0         86413808   3
4.0          86413409   2
1.0          86413018   1