In [1]:
import pandas as pd
import numpy as np

In [54]:
df=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2020_Weekend1_Problems\2020_Weekend1_Problems\2020_Problem_D_DATA\2020_Problem_D_DATA\fullevents1.xlsx')

In [4]:
df[:5]

,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventOrigin_x,EventOrigin_y,EventDestination_x,EventDestination_y
0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,0.0,0.0,66.0,89.0
1,1,Opponent1,Opponent1_D1,NaN,1H,33.730326,Duel,Air duel,34.0,11.0,22.0,0.0
2,1,Huskies,Huskies_F1,NaN,1H,33.812965,Duel,Air duel,66.0,89.0,78.0,100.0
3,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,22.0,0.0,66.0,3.0
4,1,Huskies,Huskies_D1,Huskies_F1,1H,46.323501,Pass,Head pass,34.0,97.0,59.0,95.0

In [9]:
s=pd.Series(np.arange(1,10),index=[['a','a','a','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,3]])#都是9个
s

a  1    1
   2    2
   3    3
b  1    4
   2    5
c  3    6
   1    7
d  2    8
   3    9
dtype: int32

In [10]:
s.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('c', 3),
            ('c', 1),
            ('d', 2),
            ('d', 3)],
           )

In [12]:
s['a':'b']

a  1    1
   2    2
   3    3
b  1    4
   2    5
dtype: int32

In [16]:
s[:,2]

a    2
b    5
d    8
dtype: int32

s[:,1:2]不对

In [17]:
s.unstack()

     1    2    3
a  1.0  2.0  3.0
b  4.0  5.0  NaN
c  7.0  NaN  6.0
d  NaN  8.0  9.0

In [18]:
s.unstack().stack()

a  1    1.0
   2    2.0
   3    3.0
b  1    4.0
   2    5.0
c  1    7.0
   3    6.0
d  2    8.0
   3    9.0
dtype: float64

In [24]:
data=pd.DataFrame(np.arange(12).reshape(4,3),index=[['a','a','b','b',],[1,2,1,2]],columns=[['A','A','B'],['Z','X','C']])
data

     A       B
     Z   X   C
a 1  0   1   2
  2  3   4   5
b 1  6   7   8
  2  9  10  11

In [28]:
data['B']#aZXC报错

      C
a 1   2
  2   5
b 1   8
  2  11

In [34]:
data.index.names=['row1','row2']
data.columns.names=['col1','col2']
data

col1       A       B
col2       Z   X   C
row1 row2
a    1     0   1   2
     2     3   4   5
b    1     6   7   8
     2     9  10  11

In [35]:
data.swaplevel('row1','row2')#调row的位置

col1       A       B
col2       Z   X   C
row2 row1
1    a     0   1   2
2    a     3   4   5
1    b     6   7   8
2    b     9  10  11

In [36]:
df.index

RangeIndex(start=0, stop=59271, step=1)

In [55]:
df=df.set_index(['EventOrigin_x','EventOrigin_y'])
df

,,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventDestination_x,EventDestination_y
EventOrigin_x,EventOrigin_y,,,,,,,,,,
0.0,0.0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,66.0,89.0
34.0,11.0,1,Opponent1,Opponent1_D1,NaN,1H,33.730326,Duel,Air duel,22.0,0.0
66.0,89.0,1,Huskies,Huskies_F1,NaN,1H,33.812965,Duel,Air duel,78.0,100.0
22.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,66.0,3.0
34.0,97.0,1,Huskies,Huskies_D1,Huskies_F1,1H,46.323501,Pass,Head pass,59.0,95.0
...,...,...,...,...,...,...,...,...,...,...,...
2.0,31.0,38,Huskies,Huskies_D4,NaN,2H,2790.457942,Others on the ball,Touch,0.0,32.0
100.0,100.0,38,Opponent14,Opponent14_M5,NaN,2H,2829.821084,Free Kick,Corner,88.0,47.0
12.0,53.0,38,Huskies,Huskies_D1,NaN,2H,2831.211419,Duel,Air duel,14.0,50.0
88.0,47.0,38,Opponent14,Opponent14_D7,NaN,2H,2832.434399,Duel,Air duel,86.0,50.0
86.0,50.0,38,Opponent14,Opponent14_D7,NaN,2H,2834.127168,Shot,Shot,0.0,0.0

In [57]:
df.index[1]

(34.0, 11.0)

In [58]:
df.loc[2.0]

,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventDestination_x,EventDestination_y
EventOrigin_y,,,,,,,,,,
1.0,2,Opponent2,Opponent2_M4,NaN,2H,1098.298623,Duel,Ground attacking duel,12.0,7.0
87.0,3,Huskies,Huskies_D6,NaN,1H,165.694152,Duel,Ground attacking duel,10.0,86.0
23.0,3,Huskies,Huskies_D4,NaN,1H,1524.092026,Others on the ball,Clearance,15.0,0.0
8.0,3,Opponent3,Opponent3_D4,NaN,1H,2471.375532,Others on the ball,Clearance,16.0,8.0
1.0,4,Huskies,Huskies_M1,NaN,1H,1071.210139,Duel,Ground defending duel,65.0,43.0
13.0,4,Opponent4,Opponent4_D1,NaN,1H,1721.820037,Duel,Ground loose ball duel,100.0,100.0
5.0,4,Huskies,Huskies_F2,NaN,2H,315.652229,Duel,Ground loose ball duel,51.0,95.0
1.0,4,Huskies,Huskies_M3,NaN,2H,356.258761,Duel,Ground defending duel,13.0,14.0
42.0,4,Opponent4,Opponent4_G1,NaN,2H,533.243596,Others on the ball,Touch,6.0,59.0
87.0,4,Opponent4,Opponent4_D2,NaN,2H,833.199315,Duel,Ground defending duel,3.0,91.0
13.0,4,Huskies,Huskies_G1,NaN,2H,1713.776479,Duel,Ground loose ball duel,0.0,0.0
59.0,4,Opponent4,Opponent4_D4,NaN,2H,2332.003434,Others on the ball,Touch,0.0,86.0
5.0,5,Opponent5,Opponent5_D3,NaN,2H,833.610366,Duel,Ground defending duel,14.0,0.0
50.0,5,Opponent5,Opponent5_D4,NaN,2H,2737.641555,Others on the ball,Touch,10.0,66.0
15.0,6,Huskies,Huskies_D4,NaN,1H,45.044094,Duel,Ground defending duel,6.0,18.0
61.0,6,Huskies,Huskies_D5,NaN,1H,2494.111898,Duel,Air duel,0.0,100.0
56.0,6,Huskies,Huskies_G1,NaN,1H,2674.330125,Duel,Ground loose ball duel,0.0,0.0
3.0,6,Huskies,Huskies_D4,NaN,2H,120.997563,Others on the ball,Touch,5.0,0.0
27.0,6,Opponent6,Opponent6_D1,NaN,2H,950.729783,Others on the ball,Clearance,3.0,0.0
82.0,6,Huskies,Huskies_D6,NaN,2H,1422.852690,Duel,Ground attacking duel,0.0,0.0
48.0,6,Opponent6,Opponent6_M1,NaN,2H,1487.557744,Others on the ball,Clearance,100.0,100.0
9.0,6,Opponent6,Opponent6_M2,NaN,2H,1632.995568,Others on the ball,Touch,12.0,15.0
68.0,6,Huskies,Huskies_D7,NaN,2H,2132.003125,Duel,Ground defending duel,3.0,92.0
10.0,6,Opponent6,Opponent6_M2,NaN,2H,3030.578930,Duel,Ground defending duel,2.0,4.0
4.0,6,Opponent6,Opponent6_D1,NaN,2H,3032.002581,Duel,Ground defending duel,2.0,7.0
7.0,6,Opponent6,Opponent6_M2,NaN,2H,3032.776483,Others on the ball,Touch,0.0,7.0
3.0,6,Opponent6,Opponent6_F4,NaN,2H,3075.776532,Duel,Ground defending duel,100.0,100.0
50.0,7,Huskies,Huskies_G1,NaN,1H,733.863390,Others on the ball,Touch,7.0,76.0
83.0,7,Opponent7,Opponent7_D4,NaN,2H,44.321018,Others on the ball,Clearance,100.0,100.0
10.0,7,Opponent7,Opponent7_D2,NaN,2H,280.170827,Others on the ball,Touch,0.0,11.0
29.0,7,Opponent7,Opponent7_D1,NaN,2H,2021.757761,Others on the ball,Touch,0.0,31.0
57.0,7,Opponent7,Opponent7_D4,NaN,2H,2366.595829,Others on the ball,Clearance,33.0,81.0
11.0,8,Opponent8,Opponent8_D4,NaN,2H,475.887616,Others on the ball,Clearance,4.0,0.0
74.0,8,Huskies,Huskies_D6,NaN,2H,1072.026653,Others on the ball,Touch,0.0,45.0
44.0,8,Huskies,Huskies_D1,NaN,2H,2202.717849,Others on the ball,Touch,8.0,26.0
36.0,9,Opponent9,Opponent9_G1,NaN,1H,1778.942045,Pass,Launch,39.0,29.0
74.0,11,Huskies,Huskies_D7,NaN,1H,791.205273,Pass,High pass,69.0,64.0
91.0,11,Huskies,Huskies_D7,NaN,1H,933.741161,Others on the ball,Touch,0.0,94.0
11.0,11,Opponent11,Opponent11_D2,NaN,2H,2346.153800,Duel,Ground attacking duel,100.0,100.0
90.0,11,Huskies,Huskies_D7,NaN,2H,2560.090897,Others on the ball,Touch,0.0,93.0
49.0,11,Huskies,Huskies_G1,NaN,2H,3248.536398,Others on the ball,Touch,7.0,50.0
11.0,12,Huskies,Huskies_D1,Huskies_G1,1H,1534.980526,Pass,Simple pass,2.0,33.0
33.0,12,Huskies,Huskies_G1,NaN,1H,1536.368427,Pass,Launch,47.0,19.0
0.0,12,Huskies,Huskies_D4,NaN,1H,2293.734390,Free Kick,Throw in,18.0,0.0
18.0,12,Huskies,Huskies_D1,NaN,2H,569.216438,Others on the ball,Clearance,0.0,16.0
8.0,12,Huskies,Huskies_D1,NaN,2H,785.313417,Others on the ball,Clearance,12.0,0.0
75.0,12,Huskies,Huskies_D3,NaN,2H,1537.850351,Pass,High pass,45.0,60.0
14.0,13,Opponent13,Opponent13_M5,Opponent13_M2,1H,1031.344255,Pass,Simple pass,27.0,4.0
5.0,13,Huskies,Huskies_M1,NaN,2H,2824.431238,Others on the ball,Touch,0.0,10.0
55.0,14,Opponent14,Opponent14_G1,NaN,1H,2469.066465,Pass,Launch,58.0,47.0
70.0,15,Huskies,Huskies_G1,NaN,2H,2429.896896,Others on the ball,Touch,97.0,3.0
39.0,15,Huskies,Huskies_G1,NaN,2H,2638.818162,Pass,Launch,78.0,3.0
38.0,16,Huskies,Huskies_D2,NaN,2H,526.834030,Duel,Ground loose ball duel,0.0,0.0
47.0,16,Huskies,Huskies_G1,NaN,2H,1064.861263,Duel,Ground loose ball duel,4.0,51.0
23.0,17,Huskies,Huskies_G1,NaN,2H,2122.510462,Pass,Launch,77.0,30.0
47.0,18,Opponent18,Opponent18_G1,Opponent18_D2,1H,1203.807422,Pass,Simple pass,10.0,84.0
48.0,19,Huskies,Huskies_D3,NaN,1H,573.093086,Others on the ball,Touch,0.0,0.0
29.0,19,Huskies,Huskies_G1,NaN,2H,2054.374866,Others on the ball,Touch,0.0,23.0
7.0,19,Huskies,Huskies_D5,NaN,2H,2456.373152,Others on the ball,Touch,7.0,0.0
74.0,21,Huskies,Huskies_D7,NaN,1H,427.726383,Duel,Ground defending duel,0.0,100.0
11.0,21,Huskies,Huskies_F2,NaN,2H,3031.117603,Duel,Ground defending duel,100.0,100.0
75.0,22,Opponent5,Opponent5_D1,NaN,2H,1682.350261,Duel,Ground attacking duel,0.0,100.0
63.0,22,Opponent5,Opponent5_M7,NaN,2H,1724.548638,Others on the ball,Clearance,22.0,76.0
58.0,23,Huskies,Huskies_F2,NaN,1H,2547.960697,Duel,Air duel,22.0,16.0
34.0,23,Huskies,Huskies_G1,NaN,2H,2644.572742,Others on the ball,Touch,41.0,94.0
0.0,24,Opponent19,Opponent19_D1,NaN,1H,1516.634799,Free Kick,Throw in,7.0,8.0
26.0,24,Huskies,Huskies_M3,NaN,1H,2525.752642,Duel,Ground loose ball duel,1.0,27.0
0.0,24,Huskies,Huskies_D5,NaN,1H,2567.826491,Free Kick,Throw in,26.0,25.0
76.0,25,Opponent10,Opponent10_G1,NaN,1H,1696.549263,Others on the ball,Clearance,39.0,100.0
35.0,25,Opponent10,Opponent10_D3,NaN,1H,2703.868371,Pass,Simple pass,9.0,53.0
52.0,25,Huskies,Huskies_D5,NaN,2H,2016.047716,Others on the ball,Clearance,26.0,18.0
2.0,26,Opponent9,Opponent9_D3,NaN,1H,1167.690463,Duel,Ground attacking duel,0.0,0.0
47.0,26,Huskies,Huskies_F4,NaN,1H,2350.964365,Others on the ball,Clearance,19.0,18.0
66.0,26,Opponent9,Opponent9_G2,NaN,2H,2024.712084,Others on the ball,Touch,24.0,34.0
70.0,27,Opponent12,Opponent12_D2,NaN,1H,684.493769,Others on the ball,Clearance,3.0,85.0
54.0,27,Opponent12,Opponent12_D2,NaN,1H,1564.783634,Others on the ball,Clearance,0.0,61.0
12.0,27,Opponent12,Opponent12_D7,Opponent12_F2,2H,581.377273,Pass,Simple pass,13.0,9.0
86.0,28,Huskies,Huskies_D7,NaN,2H,2735.413268,Others on the ball,Clearance,28.0,76.0
13.0,29,Huskies,Huskies_M1,Huskies_F1,2H,2225.813121,Pass,Simple pass,12.0,5.0
10.0,30,Huskies,Huskies_M6,NaN,2H,1377.477368,Others on the ball,Touch,0.0,11.0
71.0,31,Huskies,Huskies_D3,NaN,1H,124.375130,Pass,Launch,30.0,73.0
64.0,32,Opponent2,Opponent2_G1,Opponent2_D6,2H,295.278707,Pass,High pass,21.0,1.0
86.0,32,Opponent2,Opponent2_D2,NaN,2H,2661.412149,Pass,High pass,38.0,75.0
12.0,32,Opponent2,Opponent2_M3,NaN,2H,2694.158323,Duel,Ground attacking duel,14.0,32.0
54.0,33,Opponent16,Opponent16_G2,NaN,1H,1965.098471,Pass,Launch,35.0,68.0
89.0,34,Opponent18,Opponent18_M7,NaN,2H,939.386241,Duel,Ground defending duel,0.0,0.0
31.0,35,Huskies,Huskies_D3,NaN,2H,1061.944480,Others on the ball,Touch,0.0,38.0
32.0,35,Huskies,Huskies_D1,NaN,2H,2272.749167,Others on the ball,Touch,0.0,33.0
66.0,35,Huskies,Huskies_F2,NaN,2H,2304.666271,Others on the ball,Touch,0.0,78.0
95.0,36,Huskies,Huskies_F5,NaN,1H,699.099908,Pass,Simple pass,8.0,81.0
11.0,37,Opponent13,Opponent13_D2,NaN,1H,1002.849799,Pass,Simple pass,34.0,22.0
25.0,37,Opponent13,Opponent13_D2,NaN,2H,935.524383,Others on the ball,Touch,0.0,35.0
60.0,37,Huskies,Huskies_D3,NaN,2H,1428.664711,Others on the ball,Clearance,0.0,6.0
31.0,38,Huskies,Huskies_D4,NaN,2H,2790.457942,Others on the ball,Touch,0.0,32.0

In [62]:
df=df.reset_index()

In [63]:
data=df[:10]
data

,EventOrigin_x,EventOrigin_y,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventDestination_x,EventDestination_y
0,0.0,0.0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,66.0,89.0
1,34.0,11.0,1,Opponent1,Opponent1_D1,NaN,1H,33.730326,Duel,Air duel,22.0,0.0
2,66.0,89.0,1,Huskies,Huskies_F1,NaN,1H,33.812965,Duel,Air duel,78.0,100.0
3,22.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,66.0,3.0
4,34.0,97.0,1,Huskies,Huskies_D1,Huskies_F1,1H,46.323501,Pass,Head pass,59.0,95.0
5,59.0,95.0,1,Huskies,Huskies_F1,NaN,1H,47.004714,Duel,Ground loose ball duel,64.0,94.0
6,41.0,5.0,1,Opponent1,Opponent1_D1,NaN,1H,47.213716,Duel,Ground loose ball duel,36.0,6.0
7,36.0,6.0,1,Opponent1,Opponent1_M1,NaN,1H,48.487897,Pass,Simple pass,45.0,5.0
8,55.0,95.0,1,Huskies,Huskies_F1,NaN,1H,49.880983,Pass,Head pass,57.0,93.0
9,43.0,7.0,1,Opponent1,Opponent1_D1,NaN,1H,50.109404,Duel,Ground loose ball duel,47.0,11.0

In [64]:
data.T

,0,1,2,3,4,5,6,7,8,9
EventOrigin_x,0.0,34.0,66.0,22.0,34.0,59.0,41.0,36.0,55.0,43.0
EventOrigin_y,0.0,11.0,89.0,0.0,97.0,95.0,5.0,6.0,95.0,7.0
MatchID,1,1,1,1,1,1,1,1,1,1
TeamID,Huskies,Opponent1,Huskies,Opponent1,Huskies,Huskies,Opponent1,Opponent1,Huskies,Opponent1
OriginPlayerID,Huskies_G1,Opponent1_D1,Huskies_F1,Opponent1_D2,Huskies_D1,Huskies_F1,Opponent1_D1,Opponent1_M1,Huskies_F1,Opponent1_D1
DestinationPlayerID,NaN,NaN,NaN,NaN,Huskies_F1,NaN,NaN,NaN,NaN,NaN
MatchPeriod,1H,1H,1H,1H,1H,1H,1H,1H,1H,1H
EventTime,31.174681,33.730326,33.812965,42.611028,46.323501,47.004714,47.213716,48.487897,49.880983,50.109404
EventType,Free Kick,Duel,Duel,Free Kick,Pass,Duel,Duel,Pass,Pass,Duel
EventSubType,Goal kick,Air duel,Air duel,Throw in,Head pass,Ground loose ball duel,Ground loose ball duel,Simple pass,Head pass,Ground loose ball duel
EventDestination_x,66.0,22.0,78.0,66.0,59.0,64.0,36.0,45.0,57.0,47.0
EventDestination_y,89.0,0.0,100.0,3.0,95.0,94.0,6.0,5.0,93.0,11.0

In [ ]:
#data.stack().unstack()   转为层次化索引的series

In [65]:
group=df.groupby(df['EventDestination_x'])

In [67]:
type(group)

pandas.core.groupby.generic.DataFrameGroupBy

In [70]:
group.mean()

,EventOrigin_x,EventOrigin_y,MatchID,EventTime,EventDestination_y
EventDestination_x,,,,,
0.0,58.403580,49.340928,18.958503,1515.295114,14.865745
1.0,14.928571,43.714286,14.476190,1620.408198,38.142857
2.0,12.168675,39.072289,17.638554,1488.171898,38.650602
3.0,19.184049,48.245399,18.245399,1437.053437,44.601227
4.0,16.176101,46.264151,19.452830,1280.277245,48.094340
...,...,...,...,...,...
96.0,84.100000,49.944000,18.436000,1378.197482,52.652000
97.0,83.936364,49.600000,18.300000,1468.075630,52.086364
98.0,79.369128,57.926174,17.402685,1394.960928,60.959732
99.0,78.560976,53.024390,13.975610,1424.041184,59.731707
100.0,76.963074,50.904192,19.212575,1546.755998,89.577844

In [73]:
df['EventDestination_y'].groupby(df['EventDestination_x']).median()

EventDestination_x
0.0        0.0
1.0       29.5
2.0       29.0
3.0       45.0
4.0       46.0
         ...
96.0      51.0
97.0      52.5
98.0      72.0
99.0      70.5
100.0    100.0
Name: EventDestination_y, Length: 101, dtype: float64

In [76]:
df['EventDestination_y'].groupby([df['EventDestination_x'],df['EventOrigin_y']]).mean()

EventDestination_x  EventOrigin_y
0.0                 0.0               22.222222
                    1.0                0.000000
                    2.0                0.000000
                    3.0                3.333333
                    4.0                0.000000
                                        ...
100.0               96.0              86.666667
                    97.0             100.000000
                    98.0              96.250000
                    99.0             100.000000
                    100.0             92.111111
Name: EventDestination_y, Length: 9672, dtype: float64

In [91]:
pd.cut(df['EventDestination_y'],[-1,25,50,75,100],right=True,labels=['D','C','B','A'])

0        A
1        D
2        A
3        D
4        A
        ..
59266    C
59267    C
59268    C
59269    C
59270    D
Name: EventDestination_y, Length: 59271, dtype: category
Categories (4, object): ['D' < 'C' < 'B' < 'A']

In [88]:
bins=np.percentile(df['EventDestination_y'],[0,25,50,75,100])

In [90]:
#df['EventDestination_x']=pd.cut(df['EventDestination_y'],bins,labels=['D','C','B','A'])

In [ ]:
#df[(df.热门程度==‘E’)&(df。评分等级==‘A’)]

pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None,
lef_ index=False, right_index=False, sort=True,
suffixes=('_x','_y'), copy=True, indicator=False)
left:对象
right:另一个对象
on:要加入的列（名称）。必须在左、右综合对象中找到。如果不能通过 left index和 right_ index是假，将推断 Dataframes中的列的交又点为连接健
left_on:从左边的综合使用作为键列。可以是列名或数组的长度等于长度综合
right on:从正确的综合，以用作键列。可以是列名或数组的长度等于长度综合
left_ index:如果为Tue,则使用素引（行标签）从左综合作为其联接键。在与多重（层次）的综合，级别別数必须匹配联接键从右综合的数目
right index:相同用法作为正确综合 left index
how:之ー・左，右，外在、内部。默认为内部。每个方法的更详细说明请参阅：
sort:综合通过联接键按字典顺序对结果进行排序。默认值为True,设置为 False将提高性能极大地在许多情况下
suffixes:字符串后缀井不适用于重列的元组。默认值为(_x,'y).
copy:即使重新索引是不必要总是从传递的综合对象，复制的数据(默认值True)。在许多情况下不能兔，但可能会提高性能/内存使用情况。可以避免复制
上述案件有些病理但尽管如此提供此选项。
indicator:将列添加到输出综合呼吁_ merge与信息源的每一行。_ merge是绝对类型，并对观测其合并键只出现在左的综合，观测其合并键只会出现在'正确
的综合，和两个如果观察合并关健发现在两个ight_ only left_ony的值。

In [101]:
df1=df.loc[:5]
df1

,EventOrigin_x,EventOrigin_y,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventDestination_x,EventDestination_y
0,0.0,0.0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,66.0,89.0
1,34.0,11.0,1,Opponent1,Opponent1_D1,NaN,1H,33.730326,Duel,Air duel,22.0,0.0
2,66.0,89.0,1,Huskies,Huskies_F1,NaN,1H,33.812965,Duel,Air duel,78.0,100.0
3,22.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,66.0,3.0
4,34.0,97.0,1,Huskies,Huskies_D1,Huskies_F1,1H,46.323501,Pass,Head pass,59.0,95.0
5,59.0,95.0,1,Huskies,Huskies_F1,NaN,1H,47.004714,Duel,Ground loose ball duel,64.0,94.0

In [120]:
df2=df.loc[:5][['EventOrigin_x','EventOrigin_y']]
df2['z']=[1,3,5,7,9,11]
df2

   EventOrigin_x  EventOrigin_y   z
0            0.0            0.0   1
1           34.0           11.0   3
2           66.0           89.0   5
3           22.0            0.0   7
4           34.0           97.0   9
5           59.0           95.0  11

In [121]:
df2=df2.sample(frac=1)#顺序打乱但index仍对应
df2

   EventOrigin_x  EventOrigin_y   z
5           59.0           95.0  11
1           34.0           11.0   3
2           66.0           89.0   5
4           34.0           97.0   9
0            0.0            0.0   1
3           22.0            0.0   7

In [122]:
df2.index=range(len(df2))#更改index
df2

   EventOrigin_x  EventOrigin_y   z
0           59.0           95.0  11
1           34.0           11.0   3
2           66.0           89.0   5
3           34.0           97.0   9
4            0.0            0.0   1
5           22.0            0.0   7

In [117]:
# df2.loc[3,'EventOrigin_y']=97.0
# df2.loc[4,'EventOrigin_y']=10.0
# df2.loc[5,'EventOrigin_y']=10.0
# df2

AttributeError: 'float' object has no attribute 'loc'

In [123]:
#index不对应情况下df1和df2合并    用on
pd.merge(df1,df2,how='inner',on='EventOrigin_y')

,EventOrigin_x_x,EventOrigin_y,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventDestination_x,EventDestination_y,EventOrigin_x_y,z
0,0.0,0.0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,66.0,89.0,0.0,1
1,0.0,0.0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,66.0,89.0,22.0,7
2,22.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,66.0,3.0,0.0,1
3,22.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,66.0,3.0,22.0,7
4,34.0,11.0,1,Opponent1,Opponent1_D1,NaN,1H,33.730326,Duel,Air duel,22.0,0.0,34.0,3
5,66.0,89.0,1,Huskies,Huskies_F1,NaN,1H,33.812965,Duel,Air duel,78.0,100.0,66.0,5
6,34.0,97.0,1,Huskies,Huskies_D1,Huskies_F1,1H,46.323501,Pass,Head pass,59.0,95.0,34.0,9
7,59.0,95.0,1,Huskies,Huskies_F1,NaN,1H,47.004714,Duel,Ground loose ball duel,64.0,94.0,59.0,11

In [124]:
df4=df[:5]
df5=df[10:15]
df6=df[20:25]
df4

,EventOrigin_x,EventOrigin_y,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventDestination_x,EventDestination_y
0,0.0,0.0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,66.0,89.0
1,34.0,11.0,1,Opponent1,Opponent1_D1,NaN,1H,33.730326,Duel,Air duel,22.0,0.0
2,66.0,89.0,1,Huskies,Huskies_F1,NaN,1H,33.812965,Duel,Air duel,78.0,100.0
3,22.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,66.0,3.0
4,34.0,97.0,1,Huskies,Huskies_D1,Huskies_F1,1H,46.323501,Pass,Head pass,59.0,95.0

In [125]:
dff=pd.concat([df4,df5,df6])
dff

,EventOrigin_x,EventOrigin_y,MatchID,TeamID,OriginPlayerID,DestinationPlayerID,MatchPeriod,EventTime,EventType,EventSubType,EventDestination_x,EventDestination_y
0,0.0,0.0,1,Huskies,Huskies_G1,NaN,1H,31.174681,Free Kick,Goal kick,66.0,89.0
1,34.0,11.0,1,Opponent1,Opponent1_D1,NaN,1H,33.730326,Duel,Air duel,22.0,0.0
2,66.0,89.0,1,Huskies,Huskies_F1,NaN,1H,33.812965,Duel,Air duel,78.0,100.0
3,22.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,42.611028,Free Kick,Throw in,66.0,3.0
4,34.0,97.0,1,Huskies,Huskies_D1,Huskies_F1,1H,46.323501,Pass,Head pass,59.0,95.0
10,53.0,89.0,1,Huskies,Huskies_M1,Huskies_F2,1H,51.022546,Pass,Simple pass,69.0,91.0
11,69.0,91.0,1,Huskies,Huskies_F2,NaN,1H,51.624604,Pass,Simple pass,75.0,100.0
12,30.0,0.0,1,Opponent1,Opponent1_D2,NaN,1H,62.221515,Free Kick,Throw in,40.0,0.0
13,65.0,100.0,1,Huskies,Huskies_F1,NaN,1H,85.962263,Free Kick,Throw in,81.0,84.0
14,19.0,16.0,1,Opponent1,Opponent1_D2,Opponent1_G1,1H,89.008721,Pass,Simple pass,5.0,50.0
20,64.0,37.0,1,Opponent1,Opponent1_M1,NaN,1H,99.759819,Pass,Simple pass,70.0,5.0
21,30.0,95.0,1,Huskies,Huskies_D1,NaN,1H,103.356274,Pass,High pass,72.0,97.0
22,28.0,3.0,1,Opponent1,Opponent1_D1,NaN,1H,105.003815,Duel,Air duel,39.0,7.0
23,72.0,97.0,1,Huskies,Huskies_F1,NaN,1H,106.139608,Duel,Air duel,61.0,93.0
24,39.0,7.0,1,Opponent1,Opponent1_M1,NaN,1H,107.847835,Pass,Simple pass,27.0,2.0